url: https://dumpark.com
baseurl: /

# Site settings
title: dumpark data visualisation & information design
email: hello@dumpark.com
description: "Under construction: dumpark data visualisation & information design"

# Postal address (add as many lines as necessary)
address:
  - line: "Germany: Woischin & Franz GbR, Harkortstr. 144, 22765 Hamburg"
  - line: "New Zealand: Unfold Data ltd, 12 Milton St., Wellington 6023"

# Build settings
markdown: kramdown
permalink: pretty
